---
- name: Playbook to create custom EE
  hosts: controller.node
  gather_facts: false
  collections:
    - redhat_cop.ee_utilities
  pre_tasks:
    - name: Template out collection requirements
      ansible.builtin.template:
        src: requirements.yaml.j2
        dest: "{{ playbook_dir }}/__requirements.yaml"
      delegate_to: localhost

    - name: Eat the requirements file.
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/__requirements.yaml"
        name: __reqs
      delegate_to: localhost

  vars:
    ee_list:
      - name: "{{ survey_image_name }}"
        base_image: "{{ survey_base_image | default(omit, true) }}"
        bindep: "{{ survey_bindep.split('\n') }}"
        python: "{{ survey_python.split('\n') }}"
        collections: "{{ __reqs.collections }}"
        prepend: "{{ survey_prepend.split('\n') }}"
        append: "{{ survey_append.split('\n') }}"
  roles:
    - redhat_cop.ee_utilities.ee_builder
...
